#!/usr/bin/env python3
"""Build script for "List of useful tools".

Reads data.json (the only hand-authored data file) and generates:

  - compiled/items.json  items + a precomputed lowercase `search` field,
                          used by script.js for fast fuzzy search
  - compiled/tags.json   sorted, deduped unique tag list
  - README.md            regenerated from templates/readme_header.md +
                          a tag-grouped body + templates/readme_footer.md

Usage:
    python3 build.py           validate data.json, then (re)write all
                                generated files
    python3 build.py --check   validate data.json and report whether the
                                generated files are up to date, without
                                writing anything (exits non-zero if stale)

Stdlib only, no pip dependencies.
"""
import argparse
import json
import re
import sys
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parent
DATA_JSON = ROOT / "data.json"
COMPILED_DIR = ROOT / "compiled"
ITEMS_JSON = COMPILED_DIR / "items.json"
TAGS_JSON = COMPILED_DIR / "tags.json"
README_MD = ROOT / "README.md"
README_HEADER = ROOT / "templates" / "readme_header.md"
README_FOOTER = ROOT / "templates" / "readme_footer.md"

GENERATED_MARKER = "<!-- GENERATED by build.py from data.json — do not edit by hand -->"


def load_data():
    try:
        raw = DATA_JSON.read_text(encoding="utf-8")
    except FileNotFoundError:
        print(f"error: {DATA_JSON} not found", file=sys.stderr)
        sys.exit(1)
    try:
        data = json.loads(raw)
    except json.JSONDecodeError as e:
        print(f"error: {DATA_JSON} is not valid JSON: {e}", file=sys.stderr)
        sys.exit(1)
    if not isinstance(data, list):
        print(f"error: {DATA_JSON} must contain a top-level JSON array", file=sys.stderr)
        sys.exit(1)
    return data


def validate(items):
    """Return a list of human-readable violation strings (empty = valid).

    Collects every violation instead of stopping at the first one, so a
    single run tells you everything that needs fixing in data.json.
    """
    errors = []
    seen_names = {}

    for i, item in enumerate(items):
        if not isinstance(item, dict):
            errors.append(f"item #{i}: not a JSON object")
            continue

        label = item.get("name") if isinstance(item.get("name"), str) and item.get("name").strip() else f"item #{i}"

        name = item.get("name")
        if not isinstance(name, str) or not name.strip():
            errors.append(f"{label}: missing or empty 'name'")

        url = item.get("url")
        if not isinstance(url, str) or not url.strip():
            errors.append(f"{label}: missing or empty 'url'")
        elif not (url.startswith("http://") or url.startswith("https://")):
            errors.append(f"{label}: 'url' must start with http:// or https:// (got {url!r})")

        description = item.get("description")
        if not isinstance(description, str) or not description.strip():
            errors.append(f"{label}: missing or empty 'description'")

        tags = item.get("tags")
        if not isinstance(tags, list) or not tags:
            errors.append(f"{label}: 'tags' must be a non-empty list")
        else:
            for tag in tags:
                if not isinstance(tag, str) or not tag.strip():
                    errors.append(f"{label}: tags must be non-empty strings (got {tag!r})")
                elif tag != tag.lower():
                    errors.append(f"{label}: tag {tag!r} must be lowercase")

        if isinstance(name, str) and name.strip():
            key = name.strip().lower()
            if key in seen_names:
                errors.append(f"{label}: duplicate name (case-insensitive) also used by {seen_names[key]!r}")
            else:
                seen_names[key] = name

    return errors


def build_search_field(item):
    """Lowercased, whitespace-normalized name + description + tags.

    Precomputed once here at build time so the frontend never has to
    lowercase/concatenate/rebuild this per keystroke - see CLAUDE.md's
    "Fast fuzzy search" section for why that mattered.
    """
    parts = [item["name"], item["description"], *item["tags"]]
    return re.sub(r"\s+", " ", " ".join(parts).lower()).strip()


def build_items_payload(items):
    compiled = [
        {
            "name": item["name"],
            "url": item["url"],
            "description": item["description"],
            "tags": item["tags"],
            "search": build_search_field(item),
        }
        for item in items
    ]
    return {"count": len(compiled), "items": compiled}


def build_tags_payload(items):
    tags = sorted({tag for item in items for tag in item["tags"]})
    return {"tags": tags}


def build_readme_body(items):
    tags = sorted({tag for item in items for tag in item["tags"]})
    lines = [GENERATED_MARKER, ""]
    for tag in tags:
        lines.append(f"## {tag}")
        tagged = sorted((item for item in items if tag in item["tags"]), key=lambda it: it["name"].lower())
        for item in tagged:
            name, url, description = item["name"], item["url"], item["description"]
            lines.append(f'- [{name}]({url} "{name}") - {description}')
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def build_readme(items):
    header = README_HEADER.read_text(encoding="utf-8").rstrip("\n")
    footer = README_FOOTER.read_text(encoding="utf-8").lstrip("\n")
    body = build_readme_body(items)
    return f"{header}\n\n{body}\n{footer}"


def with_timestamp(payload):
    return {**payload, "generated_at": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")}


def json_text(payload):
    return json.dumps(payload, indent=2, ensure_ascii=False) + "\n"


def is_stale(path, fresh_payload, is_json):
    """Compare on-disk content to a freshly built payload, ignoring generated_at."""
    if not path.exists():
        return True
    existing = path.read_text(encoding="utf-8")
    if is_json:
        try:
            existing_payload = json.loads(existing)
        except json.JSONDecodeError:
            return True
        existing_payload.pop("generated_at", None)
        return existing_payload != fresh_payload
    return existing != fresh_payload


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument(
        "--check", action="store_true",
        help="validate and report whether generated files are up to date, without writing",
    )
    args = parser.parse_args()

    items = load_data()
    errors = validate(items)
    if errors:
        print(f"{len(errors)} validation error(s) in {DATA_JSON.name}:", file=sys.stderr)
        for e in errors:
            print(f"  - {e}", file=sys.stderr)
        sys.exit(1)

    items_payload = build_items_payload(items)
    tags_payload = build_tags_payload(items)
    readme_text = build_readme(items)

    if args.check:
        stale = []
        if is_stale(ITEMS_JSON, items_payload, is_json=True):
            stale.append(ITEMS_JSON)
        if is_stale(TAGS_JSON, tags_payload, is_json=True):
            stale.append(TAGS_JSON)
        if is_stale(README_MD, readme_text, is_json=False):
            stale.append(README_MD)
        if stale:
            print("out of date, run `python3 build.py` to regenerate:", file=sys.stderr)
            for p in stale:
                print(f"  - {p.relative_to(ROOT)}", file=sys.stderr)
            sys.exit(1)
        print("up to date.")
        return

    COMPILED_DIR.mkdir(exist_ok=True)
    ITEMS_JSON.write_text(json_text(with_timestamp(items_payload)), encoding="utf-8")
    TAGS_JSON.write_text(json_text(with_timestamp(tags_payload)), encoding="utf-8")
    README_MD.write_text(readme_text, encoding="utf-8")

    print(f"wrote {ITEMS_JSON.relative_to(ROOT)}")
    print(f"wrote {TAGS_JSON.relative_to(ROOT)}")
    print(f"wrote {README_MD.relative_to(ROOT)}")
    print(f"\n{items_payload['count']} items, {len(tags_payload['tags'])} unique tags.")


if __name__ == "__main__":
    main()
